# NextCloud: https://hub.docker.com/_/nextcloud/
# MariaDB: https://hub.docker.com/_/mariadb
# MariaDB Health Check: https://mariadb.com/kb/en/using-healthcheck-sh/

services:
  nextcloud-db:
    image: mariadb:11.7
    restart: always
    networks:
      - default
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  nextcloud:
    image: "nextcloud:31.0.2"
    restart: always
    networks:
      - default
    depends_on:
      nextcloud-db:
        condition: service_healthy
    volumes:
      - nextcloud:/var/www/html
      - storage:/var/www/html/data
      - ./config/nextcloud-apache.conf:/etc/apache2/conf-enabled/custom.conf
    environment:
      - NEXTCLOUD_ADMIN_USER=${USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    ports:
      - ${CLOUD_PORT}:80

volumes:
  nextcloud:
  storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./storage
  db:

networks:
  default: